name: static-deploy

on:
  push:
    branches:
      - main

jobs:
  static-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - run: |
          echo "User-agent: *
            Disallow: /" >> dist/robots.txt
      - run: sh scripts/bootstrap-custom-template-site.sh
      - run: npx surge dist
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
